# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWeatherApp#2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWeatherApp#2

pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'

end
